class ServerEnum:
    # Response CONSTANTS
    RESPONSE_CONNECTION_ERROR = "CONNECTION_ERROR"
    RESPONSE_SUCCESS = "SUCCESS"
    RESPONSE_DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    RESPONSE_PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    RESPONSE_EMAIL_MISMATCH = "EMAIL_MISMATCH"
    RESPONSE_EMAIL_TAKEN = "EMAIL_TAKEN"
    RESPONSE_PHONE_TAKEN = "PHONE_TAKEN"